language: node_js
node_js:
  - "8.1.2"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
script:
  - echo "test completed!"
after_script:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

notification:
  email:
    on_failure: andyppbb@gmail.com
    on_success: andyppbb@gmail.com
